[package]
name = "gget"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.40"
clap = { version = "4.0.22", features = ["derive"] }
console = "0.15"
reqwest = "0.11.6"
